<?php

namespace Buggl\MainBundle\Controller\Frontend;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MainController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Buggl\MainBundle\Controller\Frontend\MainController();
        return $instance;
    }
}
