buggl_photo:
    resource: "@BugglPhotoBundle/Resources/config/routing.yml"
    prefix:   /

buggl_main:
    resource: "@BugglMainBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
