<?php

namespace Buggl\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{
	public function getByCountryID($countryID, $isAjax = false)
	{
		$qb = $this->createQueryBuilder("city");

        $qb->select("city")
           ->where("city.country = :countryID")
           ->orderBy("city.name","ASC")
           ->setParameter("countryID",$countryID);

        if($isAjax)
        	return $qb->getQuery()->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);

        return $qb->getQuery()->getResult();
	}

    public function findAllOrderedByCountry()
    {
        $qb = $this->createQueryBuilder("city");

        $qb->select("city")
           ->addOrderBy("city.country","ASC")
           ->addOrderBy("city.name","ASC");
           
        return $qb->getQuery()->getResult();
    }
}
