<?php

namespace Buggl\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ContactUsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactUsRepository extends EntityRepository
{
    /**
     * finds all contact us message ararnged by status and date
     * @param  integer $limit []
     * @param  integer $page  []
     *
     * @return Doctrine\ORM\Tools\Pagination\Paginator
     */
    public function findAll($limit = 0, $page = 1)
    {
        $qb = $this->createQueryBuilder('contact');

        $qb->select('contact')
           ->addOrderBy('contact.status','DESC')
           ->addOrderBy('contact.dateContacted','DESC');

        if( $limit > 0 ){
            $offset = ($page - 1) * $limit;
            $qb->setFirstResult($offset)
               ->setMaxResults($limit);
        }

        $paginator = new Paginator($qb->getQuery(), true);
        return $paginator;
    }
}
