<?php

namespace Buggl\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EGuidePhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EGuidePhotoRepository extends EntityRepository
{
	public function findOneActiveByEguideAndType($eguide, $type = 1)
	{
		$qb = $this->createQueryBuilder('eGuidePhoto');
		
		$qb->select('eGuidePhoto')
		   ->where('eGuidePhoto.e_guide = :eGuide AND eGuidePhoto.type = :type AND eGuidePhoto.status = :status')
		   ->setParameter('eGuide', $eguide)
		   ->setParameter('type', $type)
		   ->setParameter('status', 1);
	
		try{
			return $qb->getQuery()->getSingleResult();
		}catch(\Doctrine\ORM\NoResultException $e) {}
		
		return null;
	}
}
