<?php

namespace Buggl\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Buggl\MainBundle\Entity\LocalAuthor;
use Buggl\MainBundle\Entity\Profile;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends EntityRepository
{
	
	public function getByLocalAuthor( LocalAuthor $localAuthor, $returnNewIfNull = false )
	{
		$qb = $this->createQueryBuilder('profile');
		
		$qb->select('profile')
		   ->where('profile.localAuthor = :localAuthor')
		   ->setParameter('localAuthor', $localAuthor);
		
		try{
			$profile = $qb->getQuery()->getSingleResult();
		}catch(\Doctrine\ORM\NoResultException $e) {
			$profile =  $returnNewIfNull ? new Profile() : null;
		}
		
		return $profile;
	}
}