<?php

namespace Buggl\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * SpotCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpotCategoryRepository extends EntityRepository
{
	public function findBySpotType(\Buggl\MainBundle\Entity\SpotType $spotType, $author = null)
	{
		$sql = "SELECT sc.* FROM spot_category as sc WHERE 1 AND sc.spot_type_id = ? AND sc.status = 1";
		if(!is_null($author))
		{
			$sql .= " UNION ALL SELECT sc.* FROM spot_category as sc WHERE 1 AND sc.spot_type_id = ? AND sc.local_author_id = ?";

			$params = array($spotType->getID(), $spotType->getID(), $author->getID());
		}
		else {
			$params = array($spotType->getID());
		}
		
		$em = $this->getEntityManager();
		$rsm = new ResultSetMappingBuilder($em);
		$rsm->addRootEntityFromClassMetadata('BugglMainBundle:SpotCategory', 'sc');
		$query = $this->_em->createNativeQuery($sql, $rsm);
		$query->setParameters($params);
		try {
			$result = $query->getResult();
		} catch(\Doctrine\ORM\NoResultException $e){
			return null;
		}
		return $result;
	}
}
