<?php

namespace Buggl\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TripThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TripThemeRepository extends EntityRepository
{
	public function findAllTheme(){
        $qb = $this->createQueryBuilder("themes");

        $qb->select("themes")
           ->orderBy('themes.name','ASC');

        return $qb->getQuery()->getResult();   
    }
	
}
