<?php

namespace Buggl\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WishlistRespository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishlistRepository extends EntityRepository
{
	public function findAllMyWish($localAuthor)
	{
		$qb=$this->createQueryBuilder("wishlist");

		$qb->select("wishlist")
			->where("wishlist.localAuthor= :localAuthor")
			->setParameter("localAuthor",$localAuthor);
		return $qb->getQuery()->getResult();
	}

	public function findIfAlreadyExist($eguide,$localAuthor)
	{

		$qb=$this->createQueryBuilder("wishlist");

		$qb->select("wishlist")
			->where("wishlist.localAuthor= :localAuthor AND wishlist.e_guide= :eguide")
			->setParameter("localAuthor", $localAuthor)
			->setParameter("eguide",$eguide);
		return $qb->getQuery()->getResult();
	}
}
