<?php

namespace Buggl\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * BugglShareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BugglShareRepository extends EntityRepository
{
	public function retrieveInvitesByStatus($status,$offset=0,$limit=0)
	{
		$qb = $this->createQueryBuilder('bugglShare');

		$qb->where('bugglShare.status = :status');
		$qb->setParameter('status', $status);

		if($limit > 0){
			$qb->setFirstResult($offset);
			$qb->setMaxResults($limit);
		}

		$qb->orderBy("bugglShare.dateInvited","DESC");

		$paginator = new Paginator($qb->getQuery(), true);

		return $paginator;
	}
}
