<?php

namespace Buggl\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EguideToGoodForRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EguideToGoodForRepository extends EntityRepository
{
	
	public function findByEguide($eguide)
	{
		$qb = $this->createQueryBuilder('eGuideToGoodFor');
		$qb->select('eGuideToGoodFor');
		$qb->where("eGuideToGoodFor.e_guide = :eGuide");
		$qb->setParameter("eGuide",$eguide);
		
		return $qb->getQuery()->getResult();
	}
}
