<?php

namespace Buggl\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Buggl\MainBundle\Entity\LocalAuthor;

/**
 * LocalPassionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalPassionRepository extends EntityRepository
{
	public function getByLocalAuthor( LocalAuthor $localAuthor)
	{
		$qb = $this->createQueryBuilder('localPassion');
		
		$qb->select('localPassion')
		   ->where('localPassion.localAuthor = :localAuthor')
		   ->setParameter('localAuthor', $localAuthor);
		
		return $qb->getQuery()->getResult();
	}
}
