<?php

namespace Buggl\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PasswordResetInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasswordResetInfoRepository extends EntityRepository
{
	
	public function findOneByUser($user)
	{
		$qb = $this->createQueryBuilder('passwordResetInfo');
		
		$qb->select('passwordResetInfo')
		   ->where('passwordResetInfo.user = :user')
		   ->setParameter('user', $user);
		
		try{
			return $qb->getQuery()->getSingleResult();
		}catch(\Doctrine\ORM\NoResultException $e) {}
		
		return null;
	}
}
