<?php

namespace Buggl\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Buggl\MainBundle\Entity\LocalAuthor;
use Buggl\MainBundle\Entity\PaypalInfo;
/**
 * PaypalInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaypalInfoRepository extends EntityRepository
{
	public function findByLocalAuthor( LocalAuthor $localAuthor, $returnNewIfNull = false )
	{
		$qb = $this->createQueryBuilder('paypalInfo');
		
		$qb->select('paypalInfo')
		   ->where('paypalInfo.localAuthor = :localAuthor')
		   ->setParameter('localAuthor', $localAuthor);
		
		try{
			$paypalInfo = $qb->getQuery()->getSingleResult();
		}catch(\Doctrine\ORM\NoResultException $e) {
			$paypalInfo =  $returnNewIfNull ? new PaypalInfo() : null;
		}
		
		return $paypalInfo;
	}
}
