<?php

namespace Buggl\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PaypalPurchaseInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaypalPurchaseInfoRepository extends EntityRepository
{
	public function countDownloadsForSeller($seller)
	{
		$qb = $this->createQueryBuilder('paypalPurchaseInfo');

		$qb->select('COUNT(paypalPurchaseInfo)');
		$qb->where('paypalPurchaseInfo.seller = :seller');
		$qb->setParameter('seller',$seller);

		return $qb->getQuery()->getSingleScalarResult();
	}

	public function sumNetAmountForSeller($seller, $guide = null)
	{
		$qb = $this->createQueryBuilder('paypalPurchaseInfo');

		$qb->select('SUM(paypalPurchaseInfo.netAmount)');
		$qb->where('paypalPurchaseInfo.seller = :seller');
		if( !is_null($guide) )
		{
			$qb->andWhere('paypalPurchaseInfo.eguide = :eguide');
			$qb->setParameter('eguide',$guide);
		}
		$qb->setParameter('seller',$seller);

		return $qb->getQuery()->getSingleScalarResult();
	}

	public function sumNetAmountForBuggl($guide = null)
	{
		$qb = $this->createQueryBuilder('paypalPurchaseInfo');

		$qb->select('SUM(paypalPurchaseInfo.bugglFee)');
		if( !is_null($guide) )
		{
			$qb->where('paypalPurchaseInfo.eguide = :eguide');
			$qb->setParameter('eguide',$guide);
		}

		return $qb->getQuery()->getSingleScalarResult();
	}

	/**
	 * Transaction of user be it selling or purchasing
	 * @param  LocalAuthor  $user   []
	 * @param  integer $offset 		[]
	 * @param  integer $limit  		[]
	 *
	 * @author Vincent Farly G. Taboada <farly.taboada>
	 */
	public function findByUser($user,$offset=0,$limit=0)
	{
		$qb = $this->createQueryBuilder('paypalPurchaseInfo');

		$qb->select('paypalPurchaseInfo');
		$qb->where('paypalPurchaseInfo.buyer = :user OR paypalPurchaseInfo.seller = :user');
		$qb->setParameter('user',$user);
		$qb->addOrderBy('paypalPurchaseInfo.dateOfTransaction','DESC');

		if($limit > 0){
			$qb->setFirstResult($offset);
			$qb->setMaxResults($limit);
		}

		$paginator = new Paginator($qb->getQuery(), true);

		return $paginator;
	}

	public function findByBuyer($user, $offset=0, $limit=0)
	{
		$qb = $this->createQueryBuilder('paypalPurchaseInfo');

		$qb->select('paypalPurchaseInfo');
		$qb->where('paypalPurchaseInfo.buyer = :buyer');
		$qb->setParameter('buyer',$user);
		$qb->addOrderBy('paypalPurchaseInfo.dateOfTransaction','DESC');

		if($limit > 0){
			$qb->setFirstResult($offset);
			$qb->setMaxResults($limit);
		}

		$paginator = new Paginator($qb->getQuery(), true);

		return $paginator;
	}

	public function findBySeller($user, $offset=0, $limit=0)
	{
		$qb = $this->createQueryBuilder('paypalPurchaseInfo');

		$qb->select('paypalPurchaseInfo');
		$qb->where('paypalPurchaseInfo.seller = :seller');
		$qb->setParameter('seller',$user);
		$qb->addOrderBy('paypalPurchaseInfo.dateOfTransaction','DESC');

		if($limit > 0){
			$qb->setFirstResult($offset);
			$qb->setMaxResults($limit);
		}

		$paginator = new Paginator($qb->getQuery(), true);

		return $paginator;
	}

	public function findOneByBuyerAndEguide($buyer, $eguide)
	{
		$qb = $this->createQueryBuilder('paypalPurchaseInfo');

		$qb->select('paypalPurchaseInfo');
		$qb->where('paypalPurchaseInfo.buyer = :buyer AND paypalPurchaseInfo.eguide = :eguide');
		$qb->setParameter('buyer',$buyer);
		$qb->setParameter('eguide',$eguide);

		try{
			return $qb->getQuery()->getSingleResult();
		}
		catch(\Doctrine\ORM\NoResultException $e) {}

		return null;
	}

	public function findOneBySellerAndEguide($seller, $eguide)
	{
		$qb = $this->createQueryBuilder('paypalPurchaseInfo');

		$qb->select('paypalPurchaseInfo');
		$qb->where('paypalPurchaseInfo.seller = :seller AND paypalPurchaseInfo.eguide = :eguide');
		$qb->setParameter('seller',$seller);
		$qb->setParameter('eguide',$eguide);

		try{
			return $qb->getQuery()->getSingleResult();
		}
		catch(\Doctrine\ORM\NoResultException $e) {}

		return null;
	}

	public function findEguideWithHighestNetAmount($limit=10,$page=1)
	{
		$qb = $this->createQueryBuilder('paypalPurchaseInfo');

		$qb->select(array("sum(paypalPurchaseInfo.amount)","paypalPurchaseInfo","sum(paypalPurchaseInfo.amount) AS total"))
		   ->addGroupBy('paypalPurchaseInfo.eguide')
		   ->orderBy('total','DESC');

		if($limit > 0){
			$offset = ($page-1)*$limit;
			$qb->setFirstResult($offset);
			$qb->setMaxResults($limit);
		}

		// $paginator = new Paginator($qb->getQuery(), true);

		// return $paginator;
		return $qb->getQuery()->getResult();
	}

	public function findEguideWithHighestNetAmountFilteredByCountry($limit=10,$page=1)
	{
		$qb = $this->createQueryBuilder('paypalPurchaseInfo');

		$qb->select(array("sum(paypalPurchaseInfo.amount)","paypalPurchaseInfo",'sum(paypalPurchaseInfo.amount) AS total'))
		   ->leftJoin("paypalPurchaseInfo.eguide","eguide")
		   ->addGroupBy('eguide.country')
		   ->orderBy('total','DESC');

		if($limit > 0){
			$offset = ($page-1)*$limit;
			$qb->setFirstResult($offset);
			$qb->setMaxResults($limit);
		}

		return $qb->getQuery()->getResult();
	}

	public function findUserRank( $country, $limit = 10, $page = 1 )
	{
		$qb = $this->createQueryBuilder('paypalPurchaseInfo');

		$qb->select(
				array(
					'count' => 'count( paypalPurchaseInfo.id )',
					'object' => 'paypalPurchaseInfo',
					'total' => 'count( paypalPurchaseInfo.id ) AS total'
				)
			);

		if( $country ){
			$qb->leftJoin('paypalPurchaseInfo.buyer','localAuthor')
			   ->innerJoin('BugglMainBundle:Location','location','WITH','location.localAuthor = localAuthor')
			   ->leftJoin('location.city','city')
			   ->leftJoin('city.country','country')
			   ->where('country.id = :country')
			   ->setParameter('country',$country);
		}


		$qb->addGroupBy('paypalPurchaseInfo.buyer')
		   ->orderBy('total','DESC');

		if($limit > 0){
			$offset = ($page-1)*$limit;
			$qb->setFirstResult($offset);
			$qb->setMaxResults($limit);
		}

		return $qb->getQuery()->getResult();
	}

	public function findBySearchFilterGuide($key,$limit=0,$page=1)
	{
		$qb = $this->createQueryBuilder("paypalPurchaseInfo");

		$qb->select('paypalPurchaseInfo')
		   ->leftJoin('paypalPurchaseInfo.eguide','eguide')
		   ->where('eguide.plainTitle LIKE :name')
		   ->setParameter('name','%'.$key.'%')
		   ->orderBy('paypalPurchaseInfo.dateOfTransaction','DESC');

		if($limit > 0){
			$offset = ($page-1)*$limit;
			$qb->setFirstResult($offset);
			$qb->setMaxResults($limit);
		}

		$paginator = new Paginator($qb->getQuery(), true);

		return $paginator;
	}

	public function findBySearchFilterSeller($key,$limit=0,$page=1)
	{
		$qb = $this->createQueryBuilder("paypalPurchaseInfo");

		$qb->select('paypalPurchaseInfo')
		   ->leftJoin('paypalPurchaseInfo.seller','localAuthor')
		   ->where('localAuthor.firstName LIKE :name OR localAuthor.lastName LIKE :name')
		   ->setParameter('name','%'.$key.'%')
		   ->orderBy('paypalPurchaseInfo.dateOfTransaction','DESC');

		if($limit > 0){
			$offset = ($page-1)*$limit;
			$qb->setFirstResult($offset);
			$qb->setMaxResults($limit);
		}

		$paginator = new Paginator($qb->getQuery(), true);

		return $paginator;
	}

	public function findBySearchFilterBuyer($key,$limit=0,$page=1)
	{
		$qb = $this->createQueryBuilder("paypalPurchaseInfo");

		$qb->select('paypalPurchaseInfo')
		   ->leftJoin('paypalPurchaseInfo.buyer','localAuthor')
		   ->where('localAuthor.firstName LIKE :name OR localAuthor.lastName LIKE :name')
		   ->setParameter('name','%'.$key.'%')
		   ->orderBy('paypalPurchaseInfo.dateOfTransaction','DESC');

		if($limit > 0){
			$offset = ($page-1)*$limit;
			$qb->setFirstResult($offset);
			$qb->setMaxResults($limit);
		}

		$paginator = new Paginator($qb->getQuery(), true);

		return $paginator;
	}

	public function findRecent($limit=0,$page=1)
	{
		$qb = $this->createQueryBuilder("paypalPurchaseInfo");

		$qb->select('paypalPurchaseInfo')
		   ->orderBy('paypalPurchaseInfo.dateOfTransaction','DESC');

		if($limit > 0){
			$offset = ($page-1)*$limit;
			$qb->setFirstResult($offset);
			$qb->setMaxResults($limit);
		}

		$paginator = new Paginator($qb->getQuery(), true);
		return $paginator;
	}

	public function countSoldGuidesBySeller(\Buggl\MainBundle\Entity\LocalAuthor $seller)
	{
		$qb = $this->createQueryBuilder("paypalPurchaseInfo");

		$qb->select('COUNT(paypalPurchaseInfo)')
			->distinct('paypalPurchaseInfo.eguide')
			->where('paypalPurchaseInfo.seller = :seller')
			->setParameter('seller',$seller);

		return $qb->getQuery()->getSingleScalarResult();
	}

	public function countBoughtGuidesByBuyer(\Buggl\MainBundle\Entity\LocalAuthor $buyer)
	{
		$qb = $this->createQueryBuilder("paypalPurchaseInfo");

		$qb->select('COUNT(paypalPurchaseInfo)')
			->distinct('paypalPurchaseInfo.eguide')
			->where('paypalPurchaseInfo.buyer = :buyer')
			->setParameter('buyer',$buyer);

		return $qb->getQuery()->getSingleScalarResult();
	}

	public function sumAmountSpent(\Buggl\MainBundle\Entity\LocalAuthor $buyer)
	{
		$qb = $this->createQueryBuilder('paypalPurchaseInfo');

		$qb->select('SUM(paypalPurchaseInfo.amount)')
			->where('paypalPurchaseInfo.buyer = :buyer')
			->setParameter('buyer',$buyer);

		return $qb->getQuery()->getSingleScalarResult();
	}
}