<?php

namespace Buggl\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends EntityRepository
{
    public function findReviewsByPKs($ids = array())
    {
        // $ids = '('.implode(',', $ids).')';

        $qb = $this->createQueryBuilder('review');

        $results = null;
        if( !empty($ids) ){
            $qb->select('review')
               ->where($qb->expr()->in('review.id',$ids));

            $results = $qb->getQuery()->getResult();    
        }        

        return $results;
    }
}
