<?php

namespace Buggl\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SpotToLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpotToLikeRepository extends EntityRepository
{
	
	/*
		Q: Why no foriegn key for spot_id?
	*/
	public function findBySpotId($spot)
	{
		$qb = $this->createQueryBuilder('spotToLike');
	
		$qb->select('spotToLike');
		$qb->leftJoin('spotToLike.spotLike','spotLike');
		$qb->where('spotToLike.spotId = :spotId AND spotLike.status = :status');
		$qb->setParameter('spotId',$spot->getId());
		$qb->setParameter('status',1);
	
		return $qb->getQuery()->getResult();
	}
}
