<?php

namespace Buggl\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Buggl\MainBundle\Entity\StripeInfo;

/**
 * StripeInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StripeInfoRepository extends EntityRepository
{
	
	public function findbyLocalAuthor($localAuthor, $returnNewIfNull = false)
	{
		$qb = $this->createQueryBuilder('stripeInfo');
		
		$qb->select('stripeInfo');
		$qb->where('stripeInfo.localAuthor = :localAuthor');
		$qb->setParameter('localAuthor', $localAuthor);
		
		try{
			$stripeInfo = $qb->getQuery()->getSingleResult();
		}catch(\Doctrine\ORM\NoResultException $e) {
			$stripeInfo =  $returnNewIfNull ? new StripeInfo() : null;
		}
		
		return $stripeInfo;
	}
}
