<?php

namespace Buggl\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function findInactiveLocals()
	{
        $qb = $this->createQueryBuilder('user');
		
		$fifteenDaysAgo = new \DateTime(date("Y-m-d H:i:s", strtotime(date("Y-m-d H:i:s"))) . " -15 days");

        $qb->select('user')
           ->where('user.lastActive < :fifteenDaysAgo AND user.lastInactiveNotificationSent < :fifteenDaysAgo')
           ->setParameter('fifteenDaysAgo',$fifteenDaysAgo);
        
        return $qb->getQuery()->getResult();
	}
}